### ISSUE TITLE
shape pattern P is not printing

### ISSUE THREAD

**Issue by prachi1234bansal** [prachi1234bansal/star-pattern#1]
package p;
class star
{
	public static void main(String args[])
	{
		int i,j;
		for (i=0;i<4;i++)
		{
			for(j=0;j<3;j++)
			{
				if((i==0&&j==0)||(i==0&&j==1)||(i==0&&j==2))
				{
					System.out.print("*"+" ");
				}
				 if((i==1&&j==1))
				{
					System.out.print("*"+" ");
				}
				else if((i==1 && j==2))
				{
					System.out.print("*"+" ");
				}
				else if((i==2&&j==0)||(i==2&&j==1)||(i==2&&j==2))
				{
					System.out.print("*"+" ");
				}
				else if(i==3&&j==0)
				{
					System.out.print("*"+" ");
				}
			}
			System.out.println();
		}
}	
}

**Comment by dbc2201** [comment]
```java
class star {
	public static void main(String[] args) {
		int i, j;
		for (i = 0; i < 4; i++) {
			for (j = 0; j < 3; j++) {
				if ((i == 0 && j == 0) || (i == 0 && j == 1) || (i == 0 && j == 2)) {
					System.out.print("" + " ");
				}
				if ((i == 1 && j == 1)) {
					System.out.print("" + " ");
				} else if ((i == 1 && j == 2)) {
					System.out.print("" + " ");
				} else if ((i == 2 && j == 0) || (i == 2 && j == 1) || (i == 2 && j == 2)) {
					System.out.print("" + " ");
				} else if (i == 3 && j == 0) {
					System.out.print("*" + " ");
				}
			}
			System.out.println();
		}
	}
}
```
---
The above is your re-formatted code, please tell me the exact nature of your problem and expected output.

**Comment by prachi1234bansal** [comment]
I want to print shape P but shape is not printing

**Comment by prachi1234bansal** [comment]
It is printing this
* * *
* *
* * *
*

**Comment by prachi1234bansal** [comment]
* * *
* *
* * *
*

**Comment by prachi1234bansal** [comment]
This code is printing another shape

**Comment by prachi1234bansal** [comment]
package p;
class star
{
	public static void main(String args[])
	{
		int i,j;
		for (i=0;i<4;i++)
		{
			for(j=0;j<3;j++)
			{
				if((i==0&&j==0)||(i==0&&j==1)||(i==0&&j==2))
				{
					System.out.print("*"+" ");
				}
				 if((i==1&&j==1))
				{
					System.out.print("*"+" ");
				}
				else if((i==1 && j==2))
				{
					System.out.print("*"+" ");
				}
				else if((i==2&&j==0)||(i==2&&j==1)||(i==2&&j==2))
				{
					System.out.print("*"+" ");
				}
				else if(i==3&&j==0)
				{
					System.out.print("*"+" ");
				}
			}
			System.out.println();
		}
}	
}
This code is not printing P shape

**Comment by dbc2201** [comment]
Instead of including `*` at specific coordinates, try removing them at, it'll be somewhat easier.
```java
class star {
	private static final int N = 4;
	public static void main(String[] args) {
		for (int i = 0; i < N; i++) {
			for (int j = 0; j < N; j++) {
				if ((i == 1 && j == 1) || (i == 3 && j == 1) || (i == 3 && j == 2) || j == 3) {
					System.out.print("  ");
				} else {
					System.out.print("* ");
				}
			}
			System.out.println();
		}
	}
}
```
Also, your class name should start from an upper-case alphabet and the class should be declared public.

**Comment by prachi1234bansal** [comment]
Thanku sir,
Now i will declare the class as public and 
class name to be started from an upper-case alphabet.
